import { ConvexHttpClient } from "convex/browser";
import { api } from "./convex/_generated/api";

// Replace with your Convex deployment URL (find it in .env.local or Convex dashboard)
const CONVEX_URL = process.env.NEXT_PUBLIC_CONVEX_URL!;

// Your exported JSON data - paste the full array here
const supabaseData = [
  [
    {
      idx: 0,
      id: 2,
      title: "Jakub Krehel",
      url: "https://jakub.kr/",
      tags: '["portfolios","inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=jakub.kr&sz=256",
      createdAt: "2025-08-26 19:45:25+00",
    },
    {
      idx: 1,
      id: 3,
      title: "Roo Code Evals",
      url: "https://roocode.com/evals",
      tags: '["benchmarks"]',
      favicon: "https://www.google.com/s2/favicons?domain=roocode.com&sz=256",
      createdAt: "2025-08-27 06:54:44+00",
    },
    {
      idx: 2,
      id: 5,
      title: "Google Fonts superfamilies",
      url: "https://anthonyhobday.com/sideprojects/googlefontsfamilies/",
      tags: '["fonts"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=anthonyhobday.com&sz=128",
      createdAt: "2025-09-02 15:58:52.367+00",
    },
    {
      idx: 3,
      id: 11,
      title: "orioncactus/pretendard",
      url: "https://github.com/orioncactus/pretendard",
      tags: '["fonts"]',
      favicon: "https://www.google.com/s2/favicons?domain=github.com&sz=256",
      createdAt: "2025-09-03 13:55:48.576+00",
    },
    {
      idx: 4,
      id: 12,
      title: "Colophon | Florian",
      url: "https://floriankiem.com/colophon",
      tags: '["inspiration","portfolios"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=floriankiem.com&sz=256",
      createdAt: "2025-09-03 13:56:03.095+00",
    },
    {
      idx: 5,
      id: 15,
      title: "Lucide Icons",
      url: "https://lucide.dev",
      tags: '["docs"]',
      favicon: "https://www.google.com/s2/favicons?domain=lucide.dev&sz=256",
      createdAt: "2025-09-15 10:49:37.007+00",
    },
    {
      idx: 6,
      id: 20,
      title: "Craft",
      url: "https://rauno.me/craft",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=rauno.me&sz=256",
      createdAt: "2025-09-15 14:08:06.05+00",
    },
    {
      idx: 7,
      id: 21,
      title: "Crafting the Next.js Website",
      url: "https://rauno.me/craft/nextjs",
      tags: '["inspiration","article"]',
      favicon: "https://www.google.com/s2/favicons?domain=rauno.me&sz=256",
      createdAt: "2025-09-15 14:08:29.23+00",
    },
    {
      idx: 8,
      id: 22,
      title: "Invisible Details of Interaction Design",
      url: "https://rauno.me/craft/interaction-design",
      tags: '["article","inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=rauno.me&sz=256",
      createdAt: "2025-09-15 14:08:57.604+00",
    },
    {
      idx: 9,
      id: 23,
      title: "missingfont",
      url: "https://www.missingfont.com/",
      tags: '["fonts"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=missingfont.com&sz=256",
      createdAt: "2025-09-15 14:09:30.92+00",
    },
    {
      idx: 10,
      id: 25,
      title: "making a vercel time machine",
      url: "https://x.com/raunofreiberg/status/1948357203322114160",
      tags: '["animations","inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=x.com&sz=256",
      createdAt: "2025-09-15 14:31:44.582+00",
    },
    {
      idx: 11,
      id: 26,
      title: "chips/tags design",
      url: "https://x.com/letskree8/status/1947218355703914746",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=x.com&sz=256",
      createdAt: "2025-09-15 14:33:18.6+00",
    },
    {
      idx: 12,
      id: 27,
      title: "Phosphor Icons",
      url: "https://phosphoricons.com/",
      tags: '["icons"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=phosphoricons.com&sz=256",
      createdAt: "2025-09-15 14:34:02.018+00",
    },
    {
      idx: 13,
      id: 28,
      title: "untitled icons",
      url: "https://www.untitledui.com/free-icons",
      tags: '["icons"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=untitledui.com&sz=256",
      createdAt: "2025-09-15 14:35:51.184+00",
    },
    {
      idx: 14,
      id: 29,
      title: "HackerRank - interviews and coding interviews",
      url: "https://www.hackerrank.com/",
      tags: '["employment"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=hackerrank.com&sz=256",
      createdAt: "2025-09-15 15:24:18.081+00",
    },
    {
      idx: 15,
      id: 30,
      title: "Higherin",
      url: "https://higherin.com/dashboard/my-hub",
      tags: '["employment"]',
      favicon: "https://www.google.com/s2/favicons?domain=higherin.com&sz=256",
      createdAt: "2025-09-15 15:24:47.878+00",
    },
    {
      idx: 16,
      id: 31,
      title: "dmytro | pqoqubbw",
      url: "https://pqoqubbw.dev/",
      tags: '["portfolios","inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=pqoqubbw.dev&sz=256",
      createdAt: "2025-09-15 15:25:29.04+00",
    },
    {
      idx: 17,
      id: 32,
      title: "Context7 - docs for llms",
      url: "https://context7.com/",
      tags: '["models"]',
      favicon: "https://www.google.com/s2/favicons?domain=context7.com&sz=256",
      createdAt: "2025-09-15 15:26:23.859+00",
    },
    {
      idx: 18,
      id: 33,
      title: "Rounded underline css",
      url: "https://codepen.io/pxco/pen/GRzemVV",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=codepen.io&sz=256",
      createdAt: "2025-09-15 15:26:58.239+00",
    },
    {
      idx: 19,
      id: 34,
      title: "Untitled",
      url: "https://x.com/pacocoursey/status/1591151080628682752",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=x.com&sz=256",
      createdAt: "2025-09-15 15:28:10.011+00",
    },
    {
      idx: 20,
      id: 35,
      title: "nice dialog",
      url: "https://x.com/pacocoursey/status/1591151080628682752",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=x.com&sz=256",
      createdAt: "2025-09-15 15:28:57.832+00",
    },
    {
      idx: 21,
      id: 36,
      title: "12 Principles of Animation",
      url: "https://www.raphaelsalaja.com/library/12-principles-of-animation",
      tags: '["article","animations"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=raphaelsalaja.com&sz=256",
      createdAt: "2025-09-15 15:31:09.313+00",
    },
    {
      idx: 22,
      id: 37,
      title: "font collections",
      url: "https://www.figma.com/design/lWrI14bRsS1axkjXRNG442/Usable-Google-Fonts?node-id=0-1&t=a23rNktl2sbM6L11-1",
      tags: '["fonts"]',
      favicon: "https://www.google.com/s2/favicons?domain=figma.com&sz=256",
      createdAt: "2025-09-15 15:31:20.68+00",
    },
    {
      idx: 23,
      id: 38,
      title: "lauridskern/open-runde",
      url: "https://github.com/lauridskern/open-runde",
      tags: '["fonts"]',
      favicon: "https://www.google.com/s2/favicons?domain=github.com&sz=256",
      createdAt: "2025-09-15 15:31:47.305+00",
    },
    {
      idx: 24,
      id: 39,
      title: "Endless design",
      url: "https://endless.design/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=endless.design&sz=256",
      createdAt: "2025-09-15 15:32:17.513+00",
    },
    {
      idx: 25,
      id: 40,
      title: "MingCute Icon - Carefully Designed Icon Library",
      url: "https://www.mingcute.com/",
      tags: '["icons"]',
      favicon: "https://www.google.com/s2/favicons?domain=mingcute.com&sz=256",
      createdAt: "2025-09-15 15:32:46.298+00",
    },
    {
      idx: 26,
      id: 41,
      title: "Cambio",
      url: "https://cambio.raphaelsalaja.com/",
      tags: '["react"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=cambio.raphaelsalaja.com&sz=256",
      createdAt: "2025-09-15 15:38:09.514+00",
    },
    {
      idx: 27,
      id: 42,
      title: "cool sidebar opening/closing animations",
      url: "https://codepen.io/avstorm/pen/PwPOgva",
      tags: '["icons","animations"]',
      favicon: "https://www.google.com/s2/favicons?domain=codepen.io&sz=256",
      createdAt: "2025-09-15 15:38:25.097+00",
    },
    {
      idx: 28,
      id: 43,
      title: "Tabler Icons",
      url: "https://tabler.io/icons",
      tags: '["icons"]',
      favicon: "https://www.google.com/s2/favicons?domain=tabler.io&sz=256",
      createdAt: "2025-09-15 15:40:33.534+00",
    },
    {
      idx: 29,
      id: 44,
      title: "Icônes",
      url: "https://icones.js.org/",
      tags: '["icons"]',
      favicon: "https://www.google.com/s2/favicons?domain=icones.js.org&sz=256",
      createdAt: "2025-09-15 15:40:59.748+00",
    },
    {
      idx: 30,
      id: 45,
      title: "Sargam Icons",
      url: "https://sargamicons.com/",
      tags: '["icons"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=sargamicons.com&sz=256",
      createdAt: "2025-09-15 15:41:47.877+00",
    },
    {
      idx: 31,
      id: 46,
      title: "Ask Computer, Inc.",
      url: "https://askcomputer.inc/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=askcomputer.inc&sz=256",
      createdAt: "2025-09-15 15:41:56.578+00",
    },
    {
      idx: 32,
      id: 47,
      title: "logo inspirations",
      url: "https://logosystem.co/animated",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=logosystem.co&sz=256",
      createdAt: "2025-09-15 15:42:43.992+00",
    },
    {
      idx: 33,
      id: 48,
      title: "spinner maker",
      url: "https://loading.io/",
      tags: '["assets"]',
      favicon: "https://www.google.com/s2/favicons?domain=loading.io&sz=256",
      createdAt: "2025-09-15 15:43:06.603+00",
    },
    {
      idx: 34,
      id: 49,
      title: "Curated Website Section Designs",
      url: "https://www.unsection.com/",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=unsection.com&sz=256",
      createdAt: "2025-09-15 15:43:18.708+00",
    },
    {
      idx: 35,
      id: 50,
      title: "designer's index - bram naus's curated design resources",
      url: "https://www.bramnaus.com/designers-index",
      tags: '["fonts","icons","inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=bramnaus.com&sz=256",
      createdAt: "2025-09-15 15:47:06.666+00",
    },
    {
      idx: 36,
      id: 51,
      title: "Gradcracker - Careers for STEM Students",
      url: "https://www.gradcracker.com/",
      tags: '["employment"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=gradcracker.com&sz=256",
      createdAt: "2025-09-15 15:47:19.957+00",
    },
    {
      idx: 37,
      id: 52,
      title: "Commit Mono. Neutral programming typeface.",
      url: "https://commitmono.com/",
      tags: '["fonts"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=commitmono.com&sz=256",
      createdAt: "2025-09-15 15:47:31.427+00",
    },
    {
      idx: 38,
      id: 53,
      title: "What are OKLCH colors?",
      url: "https://jakub.kr/components/oklch-colors",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=jakub.kr&sz=256",
      createdAt: "2025-09-15 15:47:42.563+00",
    },
    {
      idx: 39,
      id: 54,
      title: "Terminal-Bench",
      url: "https://www.tbench.ai/leaderboard",
      tags: '["inspiration","benchmarks","models"]',
      favicon: "https://www.google.com/s2/favicons?domain=tbench.ai&sz=256",
      createdAt: "2025-09-15 15:48:09.504+00",
    },
    {
      idx: 40,
      id: 55,
      title: "GreatFrontEnd",
      url: "https://www.greatfrontend.com/",
      tags: '["employment"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=greatfrontend.com&sz=256",
      createdAt: "2025-09-15 15:48:13.364+00",
    },
    {
      idx: 41,
      id: 56,
      title: "gemini 2.5 heavy",
      url: "https://ai.studio/apps/drive/1gkSlAtr2jVrsO6ULHb2gV2hAjA1tIU-j",
      tags: '["tools","models"]',
      favicon: "https://www.google.com/s2/favicons?domain=ai.studio&sz=256",
      createdAt: "2025-09-15 15:53:58.46+00",
    },
    {
      idx: 42,
      id: 57,
      title: "Sandpack",
      url: "https://sandpack.codesandbox.io/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=sandpack.codesandbox.io&sz=256",
      createdAt: "2025-09-16 13:57:04.571+00",
    },
    {
      idx: 43,
      id: 58,
      title: "Orchids - The AI Fullstack Engineer",
      url: "https://www.orchids.app/",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=orchids.app&sz=256",
      createdAt: "2025-09-16 18:38:34.576+00",
    },
    {
      idx: 44,
      id: 59,
      title: "CareerSet - Intelligent Career Solutions",
      url: "https://careerset.com",
      tags: '["employment"]',
      favicon: "https://www.google.com/s2/favicons?domain=careerset.com&sz=256",
      createdAt: "2025-09-17 13:50:01.304+00",
    },
    {
      idx: 45,
      id: 60,
      title: "Prompts for students",
      url: "https://chatgpt.com/use-cases/students",
      tags: '["useful","article"]',
      favicon: "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=256",
      createdAt: "2025-09-17 19:29:13.416+00",
    },
    {
      idx: 46,
      id: 61,
      title: "Web Interface Guidelines",
      url: "https://vercel.com/design/guidelines",
      tags: '["article","design"]',
      favicon: "https://www.google.com/s2/favicons?domain=vercel.com&sz=256",
      createdAt: "2025-09-19 08:20:19.372+00",
    },
    {
      idx: 47,
      id: 62,
      title: "nuqs - state in URL",
      url: "https://nuqs.dev/",
      tags: '["react"]',
      favicon: "https://www.google.com/s2/favicons?domain=nuqs.dev&sz=256",
      createdAt: "2025-09-19 08:20:48.559+00",
    },
    {
      idx: 48,
      id: 63,
      title: "2022 Top 100 Internship Programs",
      url: "https://www.nationalinternday.com/2022-top-100-internship-programs",
      tags: '["employment"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=nationalinternday.com&sz=256",
      createdAt: "2025-09-19 11:39:29.139+00",
    },
    {
      idx: 49,
      id: 64,
      title: "Neue Montreal",
      url: "https://pangrampangram.com/products/neue-montreal",
      tags: '["fonts"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=pangrampangram.com&sz=256",
      createdAt: "2025-09-19 19:20:47.182+00",
    },
    {
      idx: 50,
      id: 65,
      title: "Dither Plugin",
      url: "https://dither.floriankiem.com/",
      tags: '["tailwind","react","plugins","tools"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=dither.floriankiem.com&sz=256",
      createdAt: "2025-09-20 09:27:21.776+00",
    },
    {
      idx: 51,
      id: 66,
      title: "Grid zoomies",
      url: "https://cdpn.io/pen/debug/wBMvNaN",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=cdpn.io&sz=256",
      createdAt: "2025-09-20 11:46:01.328+00",
    },
    {
      idx: 52,
      id: 67,
      title: "Skiper UI - Un-common Components for shadcn/ui",
      url: "https://skiper-ui.com/",
      tags: '["inspiration","react"]',
      favicon: "https://www.google.com/s2/favicons?domain=skiper-ui.com&sz=256",
      createdAt: "2025-09-21 10:57:07.885+00",
    },
    {
      idx: 53,
      id: 68,
      title: "Animated Sign-In Dialog",
      url: "https://jakub.kr/components/sign-in-dialog",
      tags: '["article","react"]',
      favicon: "https://www.google.com/s2/favicons?domain=jakub.kr&sz=256",
      createdAt: "2025-09-22 18:09:22.039+00",
    },
    {
      idx: 54,
      id: 69,
      title: "Operating System in 1,000 Lines | OS in 1,000 Lines",
      url: "https://operating-system-in-1000-lines.vercel.app/en/",
      tags: '["inspiration","build","useful"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=operating-system-in-1000-lines.vercel.app&sz=256",
      createdAt: "2025-09-25 10:48:10.849+00",
    },
    {
      idx: 55,
      id: 70,
      title: "minimalist websites gallery",
      url: "https://deadsimplesites.com/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=deadsimplesites.com&sz=256",
      createdAt: "2025-09-28 11:04:19.89+00",
    },
    {
      idx: 56,
      id: 71,
      title: "self hosting next.js",
      url: "https://www.flightcontrol.dev/blog/secret-knowledge-to-self-host-nextjs",
      tags: '["article","guide"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=flightcontrol.dev&sz=256",
      createdAt: "2025-09-30 08:12:41.783+00",
    },
    {
      idx: 57,
      id: 72,
      title: "Nice button animations and portfolio",
      url: "https://x.com/samitkapoorr/status/1973068142680141854",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=x.com&sz=256",
      createdAt: "2025-10-06 15:36:27.538+00",
    },
    {
      idx: 58,
      id: 73,
      title: "UXfolio - Fast & easy UX portfolio building",
      url: "https://uxfol.io/",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=uxfol.io&sz=256",
      createdAt: "2025-10-08 10:28:53.552+00",
    },
    {
      idx: 59,
      id: 75,
      title: "Oakline Studio",
      url: "https://oakline.studio/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=oakline.studio&sz=256",
      createdAt: "2025-10-08 15:00:59.234+00",
    },
    {
      idx: 60,
      id: 76,
      title: "Untitled",
      url: "https://un.ms/",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=un.ms&sz=256",
      createdAt: "2025-10-09 17:26:03.94+00",
    },
    {
      idx: 61,
      id: 77,
      title: "paper-design/paper-mono",
      url: "https://github.com/paper-design/paper-mono",
      tags: '["fonts"]',
      favicon: "https://www.google.com/s2/favicons?domain=github.com&sz=256",
      createdAt: "2025-10-09 17:26:48.033+00",
    },
    {
      idx: 62,
      id: 78,
      title: "Photo Gradient",
      url: "https://photogradient.com/",
      tags: '["tools"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=photogradient.com&sz=256",
      createdAt: "2025-10-11 18:13:07.687+00",
    },
    {
      idx: 63,
      id: 79,
      title: "Software Engineer's Resume Checklist",
      url: "https://map.sistilli.dev/public/coding/Software+Engineer's+Resume+Checklist",
      tags: '["employment"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=map.sistilli.dev&sz=256",
      createdAt: "2025-10-11 19:39:21.814+00",
    },
    {
      idx: 64,
      id: 80,
      title: "Soren Blank — Builder & Explorer",
      url: "https://sorenblank.com/",
      tags: '["inspiration","portfolios"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=sorenblank.com&sz=256",
      createdAt: "2025-10-12 09:06:35.334+00",
    },
    {
      idx: 65,
      id: 81,
      title: "Untitled",
      url: "https://work.cosmos.so/#roles",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=work.cosmos.so&sz=256",
      createdAt: "2025-10-15 11:51:51.641+00",
    },
    {
      idx: 66,
      id: 82,
      title: "Design books for beginners",
      url: "https://anthonyhobday.com/blog/20251015.html",
      tags: '["useful","inspiration","article","guide","fonts"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=anthonyhobday.com&sz=256",
      createdAt: "2025-10-15 18:39:22.753+00",
    },
    {
      idx: 67,
      id: 83,
      title: "EchoTab Browser Extension",
      url: "https://echotab.buka.studio/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=echotab.buka.studio&sz=256",
      createdAt: "2025-10-15 18:44:01.184+00",
    },
    {
      idx: 68,
      id: 84,
      title: "Untitled",
      url: "https://marijanapav.com/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=marijanapav.com&sz=256",
      createdAt: "2025-10-15 18:51:17.886+00",
    },
    {
      idx: 69,
      id: 85,
      title: "Overview | components.build",
      url: "https://www.components.build/",
      tags: '["react","article","guide"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=components.build&sz=256",
      createdAt: "2025-10-15 22:12:46.714+00",
    },
    {
      idx: 70,
      id: 86,
      title: "Evaluating Long Context (Reasoning) Ability | wh",
      url: "https://nrehiew.github.io/blog/long_context/",
      tags: '["benchmarks"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=nrehiew.github.io&sz=256",
      createdAt: "2025-10-17 10:45:19.837+00",
    },
    {
      idx: 71,
      id: 87,
      title: "React UI with shadcn/ui + Radix + Tailwind",
      url: "https://vercel.com/academy/shadcn-ui",
      tags: '["article","react","guide"]',
      favicon: "https://www.google.com/s2/favicons?domain=vercel.com&sz=256",
      createdAt: "2025-10-17 22:47:18.491+00",
    },
    {
      idx: 72,
      id: 88,
      title: "Tiago da Silva",
      url: "https://x.com/usernametiago/status/1979198195704926267?s=12",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=x.com&sz=256",
      createdAt: "2025-10-18 17:18:06.56+00",
    },
    {
      idx: 73,
      id: 89,
      title: "Forms",
      url: "https://ui.shadcn.com/docs/forms",
      tags: '["guide","react","article"]',
      favicon: "https://www.google.com/s2/favicons?domain=ui.shadcn.com&sz=256",
      createdAt: "2025-10-18 18:04:58.154+00",
    },
    {
      idx: 74,
      id: 90,
      title: "A new (or rather, old) approach to typography on the web",
      url: "https://www.daybreak.studio/writing/adaline-typography",
      tags: '["design","typography","article"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=daybreak.studio&sz=256",
      createdAt: "2025-10-21 14:20:59.97+00",
    },
    {
      idx: 75,
      id: 91,
      title: "Build Your Own Database",
      url: "https://www.nan.fyi/database",
      tags: '["article"]',
      favicon: "https://www.google.com/s2/favicons?domain=nan.fyi&sz=256",
      createdAt: "2025-10-21 15:13:09.072+00",
    },
    {
      idx: 76,
      id: 92,
      title: "Dieter Rams: The Complete Works",
      url: "https://www.curated.supply/products/dieter-rams-the-complete-works",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=curated.supply&sz=256",
      createdAt: "2025-10-26 16:38:40.065+00",
    },
    {
      idx: 77,
      id: 93,
      title: "Internship and career guide (Very Good)",
      url: "https://collegesaucegod.notion.site/DREAM-INTERNSHIP-CAREER-SAUCE-30201061fe6444c39ba78382b3e2970b",
      tags: '["employment"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=collegesaucegod.notion.site&sz=256",
      createdAt: "2025-10-27 12:04:15.832+00",
    },
    {
      idx: 78,
      id: 94,
      title: "Email finder",
      url: "https://hunter.io/dashboard",
      tags: '["employment"]',
      favicon: "https://www.google.com/s2/favicons?domain=hunter.io&sz=256",
      createdAt: "2025-10-27 12:05:14.975+00",
    },
    {
      idx: 79,
      id: 95,
      title: "rsms",
      url: "https://rsms.me/",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=rsms.me&sz=256",
      createdAt: "2025-10-28 11:18:19.541+00",
    },
    {
      idx: 80,
      id: 96,
      title: "LLTG",
      url: "https://lltg.co/",
      tags: '["inspiration"]',
      favicon: "https://www.google.com/s2/favicons?domain=lltg.co&sz=256",
      createdAt: "2025-11-03 14:37:00.719+00",
    },
    {
      idx: 81,
      id: 97,
      title: "Optimising docker image",
      url: "https://blog.prateekjain.dev/a-step-by-step-guide-to-docker-image-optimisation-reduce-size-by-over-95-d90bcab3819d",
      tags: '["article"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=blog.prateekjain.dev&sz=256",
      createdAt: "2025-11-14 22:02:14.946+00",
    },
    {
      idx: 82,
      id: 98,
      title: "cool shapes",
      url: "https://coolshap.es/?vjy",
      tags: '["tools","design"]',
      favicon: "https://www.google.com/s2/favicons?domain=coolshap.es&sz=256",
      createdAt: "2025-11-17 13:59:48.138+00",
    },
    {
      idx: 83,
      id: 99,
      title: "Fontshare: Quality Fonts. Free.",
      url: "https://fontshare.com/",
      tags: '["fonts"]',
      favicon: "https://www.google.com/s2/favicons?domain=fontshare.com&sz=256",
      createdAt: "2025-11-17 14:00:24.688+00",
    },
    {
      idx: 84,
      id: 100,
      title: "react native animations inspirations",
      url: "https://makeitanimated.dev/",
      tags: '["design","animations","inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=makeitanimated.dev&sz=256",
      createdAt: "2025-11-17 14:01:31.835+00",
    },
    {
      idx: 85,
      id: 101,
      title: "Untitled",
      url: "https://landingly.co",
      tags: '["inspiration","design"]',
      favicon: "https://www.google.com/s2/favicons?domain=landingly.co&sz=256",
      createdAt: "2025-11-17 14:03:11.066+00",
    },
    {
      idx: 86,
      id: 102,
      title: "Text highlighter",
      url: "https://text-highlighter-x.vercel.app/",
      tags: '["design","inspiration","animations"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=text-highlighter-x.vercel.app&sz=256",
      createdAt: "2025-11-20 10:11:43.702+00",
    },
    {
      idx: 87,
      id: 103,
      title: "components for better auth",
      url: "https://auth.uprizing.me/",
      tags: '["react","useful"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=auth.uprizing.me&sz=256",
      createdAt: "2025-11-20 14:43:46.818+00",
    },
    {
      idx: 88,
      id: 104,
      title: "How shaders work",
      url: "https://www.makingsoftware.com/chapters/shaders#definition-matrix-multiplication",
      tags: '["article"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=makingsoftware.com&sz=256",
      createdAt: "2025-11-24 16:01:51.232+00",
    },
    {
      idx: 89,
      id: 105,
      title:
        "AI Model Benchmarks Nov 2025 | Compare GPT-5, Claude 4.5, Gemini 2.5, Grok 4 | LM Council",
      url: "https://lmcouncil.ai/benchmarks",
      tags: '["models","useful"]',
      favicon: "https://www.google.com/s2/favicons?domain=lmcouncil.ai&sz=256",
      createdAt: "2025-11-24 16:28:47.942+00",
    },
    {
      idx: 90,
      id: 106,
      title: "Malta 2025 Offsite",
      url: "https://offsite.attio.com/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=offsite.attio.com&sz=256",
      createdAt: "2025-11-24 16:32:47.514+00",
    },
    {
      idx: 91,
      id: 107,
      title: "Mackenzie Child",
      url: "https://www.mackenziechild.me/",
      tags: '["inspiration"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=mackenziechild.me&sz=256",
      createdAt: "2025-11-27 00:27:02.075+00",
    },
    {
      idx: 92,
      id: 108,
      title: "cool popover menu for bookmarks",
      url: "https://x.com/tcosta/status/1984312905953640938/photo/1",
      tags: "[]",
      favicon: "https://www.google.com/s2/favicons?domain=x.com&sz=256",
      createdAt: "2025-11-27 14:06:48.812+00",
    },
    {
      idx: 93,
      id: 109,
      title: "Using Shadows Instead of Borders",
      url: "https://jakub.kr/work/shadows",
      tags: '["article"]',
      favicon: "https://www.google.com/s2/favicons?domain=jakub.kr&sz=256",
      createdAt: "2025-11-27 17:51:06.517+00",
    },
    {
      idx: 94,
      id: 110,
      title: "How to Never Get Overstimulated Again",
      url: "https://www.noahryan.co/p/how-to-never-get-overstimulated-again",
      tags: '["article","useful"]',
      favicon: "https://www.google.com/s2/favicons?domain=noahryan.co&sz=256",
      createdAt: "2025-11-29 10:56:58.719+00",
    },
    {
      idx: 95,
      id: 111,
      title: "dnd kit – a modern drag and drop toolkit for React",
      url: "https://dndkit.com/",
      tags: '["react"]',
      favicon: "https://www.google.com/s2/favicons?domain=dndkit.com&sz=256",
      createdAt: "2025-11-30 11:11:47.46+00",
    },
    {
      idx: 96,
      id: 112,
      title: "Basic Probability",
      url: "https://seeing-theory.brown.edu/basic-probability/index.html",
      tags: '["article","useful"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=seeing-theory.brown.edu&sz=256",
      createdAt: "2025-11-30 22:03:15.022+00",
    },
    {
      idx: 97,
      id: 113,
      title: "Good websites",
      url: "https://brianlovin.com/sites",
      tags: '["inspiration","design","collection"]',
      favicon:
        "https://www.google.com/s2/favicons?domain=brianlovin.com&sz=256",
      createdAt: "2025-12-01 19:48:36.744+00",
    },
  ],
];

async function importBookmarks() {
  if (supabaseData.length === 0) {
    console.log(
      "No bookmarks to import. Paste your JSON data into supabaseData array."
    );
    return;
  }

  const client = new ConvexHttpClient(CONVEX_URL);

  // Flatten if nested array, then transform to only include fields we need
  const flatData = Array.isArray(supabaseData[0])
    ? supabaseData.flat()
    : supabaseData;
  const bookmarks = flatData.map((item: any) => ({
    title: item.title,
    url: item.url,
    tags: item.tags, // Keep as JSON string, mutation will parse it
  }));

  console.log(`Importing ${bookmarks.length} bookmarks...`);

  const result = await client.mutation(api.bookmarks.importBookmarks, {
    bookmarks,
  });

  console.log(`✓ Successfully imported ${result.imported} bookmarks!`);
}

importBookmarks().catch(console.error);
